### ISSUE TITLE
0.7dev

### ISSUE THREAD

**Issue by KC2712** [mabuchilab/NiceLib#12]
Hey guys,

We've been using the 0.7dev version to control a spectrometer while also using instrumental package.
Do you guys have a timeline on when the 0.7 version will be the pip pull down version?

Kieren

**Comment by natezb** [comment]
Hi there. I was just putting together the changelog this past weekend, so good timing! I'd say we can probably release sometime in the next week or so.

**Comment by KC2712** [comment]
Hi Nate,

That's great. Good timing indeed. Thanks for the update

**Comment by natezb** [comment]
After much fiddling with GitHub Actions, 0.7 is now released and available on PyPI. Let me know if you have any issues.
