### ISSUE TITLE
Add support for "static methods" for NiceObjects

### ISSUE THREAD

**Issue by natezb** [mabuchilab/NiceLib#5]
If a library is written using `C++`, but provides `C`-level bindings, it may expose functions which are the equivalent of static methods. It would be nice to add some kind of flag to allow adding these static methods within a `NiceObjectDef`. Currently, the functions can only be wrapped at the top library-level.

**Comment by Tillsten** [comment]
Even in some not so well written C-libs some functions are not taking the handle as the first argument. Sometimes some functions are better fitting to niceobj despite not taking a handle.

**Comment by natezb** [comment]
This is implemented as-of  38e150d
