### ISSUE TITLE
Bypass find_library when possible

### ISSUE THREAD

**Issue by natezb** [mabuchilab/NiceLib#6]
`ctypes.util.find_library` doesn't always work that well, so it may be nice to allow developers to hard-code a lib's path (at least when getting started). Currently every lib name is run through `find_library`. Instead, we should bypass this when the lib name uses an absolute path.

**Comment by Tillsten** [comment]
Looking at code I think this can be closed correct?

**Comment by natezb** [comment]
It does appear so, closing...
